### ISSUE TITLE
A PHP Error was encountered 

### ISSUE THREAD

**Issue by p3nj** [erikperttu/Code-Igniter-Reddit-Clone#2]
A PHP Error was encountered

Severity: Warning

Message: Invalid argument supplied for foreach()

Filename: libraries/core.php

Line Number: 122

**Comment by VincentRaia** [comment]
Ever come across a solution to this?

**Comment by erikperttu** [comment]
I assume that its a problem in the Code igniter code base. So it should have been fixed by now (I think)
